server.servlet.context-path: /job
server.port: ${SERVER_PORT}
server.max-http-header-size: 2MB

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_RPT_ETL}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    kubernetes:
      enabled: false
      ribbon:
        mode: SERVICE

ribbon:
  KubernetesNamespace: ${K8S_NAMESPACE:default}
  ServerListRefreshInterval: 5000

feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
  jc-gateway:
    url: ${FEIGN_GATEWAY_URL:http://localhost:7001}
  jc-base:
    url: ${FEIGN_BASE_URL:http://localhost:7201}

jc:
  api:
    local:
      gateway: http://${PF_SERVER_DOMAIN}