server.servlet.context-path: /
spring.main.allow-bean-definition-overriding: true
jc.cache.redis.dbName: ${REDIS_DBNAME:jc-test}
spring.redis.database: ${REDIS_DATABASE:11}
server.port: ${SERVER_PORT}
server.jetty.max-http-form-post-size: 20MB
server.max-http-header-size: 2MB
spring.redis.host: ${REDIS_HOST:127.0.0.1}
spring.redis.lettuce:
  pool:
    max-active: 8
    max-idle: 8
    max-wait: -1ms
    min-idle: 0
  shutdown-timeout: 100ms
spring.redis:
  port: ${REDIS_PORT:6379}
         
application:
         resource:
                loadsort: jc-log-service,jc-log-core,jc-core
         ram-cache-expire: 300 # 默认本地存缓存时间（秒），本机设为3秒，正式网设为5分钟
         dev: false # true|false 表示开启dev模式，用于开发使用配置通用选项,正式环境不可为true，可没有此配置项
         log-to-console: false # true|false 是否打印SQL等系统调测信息，一般开发环境设true，正式环境设false
         
jc.default:
    datasource:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_LOG}?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 1
      maxActive: 200
      maxWait: 60000

jc.base:
    datasource:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_BASE}?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT%2B8

jc.enterprise:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_ENTERPRISE}?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT%2B8
spring:
  cloud:
    kubernetes:
      enabled: false
      ribbon:
        mode: SERVICE

ribbon:
  KubernetesNamespace: ${K8S_NAMESPACE:default}
  ServerListRefreshInterval: 5000

feign:
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
  jc-gateway:
    url: ${FEIGN_GATEWAY_URL:http://localhost:7001}
  jc-base:
    url: ${FEIGN_BASE_URL:http://localhost:7201}

jc:
  api:
    local:
      gateway: http://${PF_SERVER_DOMAIN}